CREATE TABLE USUARIOS (
  ID_U NUMBER(20)
    CONSTRAINT USUARIOS_PK PRIMARY KEY,
  USUARIO VARCHAR2(30)
    CONSTRAINT USUARIOS_UK1 UNIQUE
    CONSTRAINT USUARIOS_NN1 NOT NULL,
  E_MAIL VARCHAR2(60)
    CONSTRAINT USUARIOS_UK2 UNIQUE
    CONSTRAINT USUARIOS_NN2 NOT NULL,
  NOMBRE VARCHAR2(30)
    CONSTRAINT USUARIOS_NN3 NOT NULL,
  APELLIDO1 VARCHAR2(30)
    CONSTRAINT USUARIOS_NN4 NOT NULL,
  APELLIDO2 VARCHAR2(30),
  PASSW VARCHAR2(100)
    CONSTRAINT USUARIOS_NN5 NOT NULL
);

CREATE TABLE CONTACTOS (
ID_U NUMBER(20),
CONTACTO NUMBER(20),
CONSTRAINT CONTACTOS_PK PRIMARY KEY (ID_U,CONTACTO),
CONSTRAINT CONTACTOS_FK1 FOREIGN KEY (ID_U) REFERENCES USUARIOS ON DELETE CASCADE,
CONSTRAINT CONTACTOS_FK2 FOREIGN KEY (CONTACTO) REFERENCES USUARIOS(ID_U) ON DELETE CASCADE
);
CREATE TABLE POST
(
  PID         NUMBER(20)
    CONSTRAINT POST_PK PRIMARY KEY,
  TEXTO       VARCHAR2(1000)
    CONSTRAINT POST_NN1 NOT NULL,
  PUBLICACION DATE CONSTRAINT POST_CK1 CHECK(PUBLICACION>TO_DATE('02/02/2017','dd/mm/yyyy'))
    CONSTRAINT POST_NN3 NOT NULL,
  DURACION    INTERVAL DAY TO SECOND
    CONSTRAINT POST_NN4 NOT NULL,
  ID_U        NUMBER(20)
    CONSTRAINT POST_NN2 NOT NULL
    CONSTRAINT POST_FK1 REFERENCES USUARIOS ON DELETE CASCADE,
  PID_REL     NUMBER(20)
    CONSTRAINT POST_FK2 REFERENCES POST
);
CREATE TABLE SER_VISIBLE(
  ID_U NUMBER(20),
  CONTACTO NUMBER(20),
  PID NUMBER(20),
  CONSTRAINT SER_VISIBLE_PK PRIMARY KEY (ID_U,CONTACTO,PID),
  CONSTRAINT SER_VISIBLE_FK1 FOREIGN KEY (ID_U,CONTACTO) REFERENCES CONTACTOS(ID_U,CONTACTO) ,
  CONSTRAINT SER_VISIBLE_FK2 FOREIGN KEY (PID) REFERENCES POST ON DELETE CASCADE
);
ALTER TABLE CONTACTOS ADD CONSTRAINT CONTACTOS_CK1 CHECK ( ID_U!=CONTACTO);

ALTER TABLE POST ADD CONSTRAINT POST_CK2 CHECK ( DURACION<INTERVAL '30'minute);

ALTER TABLE SER_VISIBLE RENAME TO COMPARTIR;

ALTER TABLE USUARIOS RENAME CONSTRAINT USARIOS_PK TO SUPERCLAVE;

ALTER TABLE POST MODIFY (PUBLICACION DEFAULT SYSDATE);

ALTER TABLE USUARIOS MODIFY (PASSW DEFAULT 12345);

INSERT INTO USUARIOS(ID_U,NOMBRE,APELLIDO1,APELLIDO2,USUARIO,E_MAIL) VALUES
(1,'Ramon','Garcia','Ortigal','ramongar','ramon@hotmail.com');
INSERT INTO USUARIOS(ID_U,NOMBRE,APELLIDO1,USUARIO,E_MAIL) VALUES
(2,'Lourdes','Atienza','lurdita','lurdita@bbc.co.uk');
INSERT INTO USUARIOS(ID_U,NOMBRE,APELLIDO1,APELLIDO2,USUARIO,E_MAIL) VALUES
(3,'Marisol','Jimenez','del oso','marioso','marioso19@yahoo.com');

INSERT INTO USUARIOS(ID_U,NOMBRE,APELLIDO1,APELLIDO2,USUARIO,E_MAIL) VALUES
(4,'Francisco','serrano','calvo','sercal','sercal1980@gmail.com')

COMMIT;
